name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v10.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: "github-actions[bot]"
        git_committer_email: "github-actions[bot]@users.noreply.github.com"

  debug:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Debug outputs
      run: |
        echo "Released: '${{ needs.release.outputs.released }}'"
        echo "Version: '${{ needs.release.outputs.version }}'"
        echo "Tag: '${{ needs.release.outputs.tag }}'"
        echo "Type check: ${{ needs.release.outputs.released == 'true' }}"
        echo "Bool check: ${{ needs.release.outputs.released == true }}"

  publish:
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/publish.yml
    with:
      released: ${{ needs.release.outputs.released }}
      version: ${{ needs.release.outputs.version }}
      tag: ${{ needs.release.outputs.tag }}
    secrets: inherit
